openapi: 3.0.0
info:
  title: User API
  version: "1.0"
paths:
  /users:
    get:
      summary: Get all users
      operationId: end_points.get_users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: object
    
    put:
      summary: Put all users
      operationId: end_points.put_users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string

      responses:
        '200':
          description: Successfully added users
          content:
            application/json:
              schema:
                type: object

  /test_endpoint:
    get:
      summary: Endpoint
      operationId: end_points.test_endpoint
      responses:
        '200':
          description: Return test response
